#ifndef NUMBERDEFINE_H
#define NUMBERDEFINE_H

#define SERVER_SOCKET_PORT 9988

#define BUFFER_LENGTH 1024
#define NAME_LENGTH 20
#define PSWD_LENGTH 20

#define NUMBER_FRIEND_TOTAL 512

#endif // NUMBERDEFINE_H
